CREATE TABLE IF NOT EXISTS llx_dolivoucher_sequence (
	rowid INTEGER AUTO_INCREMENT PRIMARY KEY,
	entity INTEGER DEFAULT 1 NOT NULL,
	sequence_type VARCHAR(32) NOT NULL,
	sequence_year SMALLINT NOT NULL,
	next_value INTEGER DEFAULT 1 NOT NULL,
	tms TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=innodb;
