CREATE TABLE IF NOT EXISTS llx_dolivoucher_series (
	rowid INTEGER AUTO_INCREMENT PRIMARY KEY,
	entity INTEGER DEFAULT 1 NOT NULL,
	ref VARCHAR(32) NOT NULL,
	generation_key VARCHAR(64) NOT NULL,
	sequence_year SMALLINT NOT NULL,
	fk_portfolio INTEGER NOT NULL,
	label VARCHAR(255) NULL,
	quantity INTEGER NOT NULL,
	face_value DECIMAL(24,8) NOT NULL,
	date_expiration DATETIME NULL,
	status INTEGER DEFAULT 0 NOT NULL,
	generated_count INTEGER DEFAULT 0 NOT NULL,
	printed_count INTEGER DEFAULT 0 NOT NULL,
	prepared_count INTEGER DEFAULT 0 NOT NULL,
	delivered_count INTEGER DEFAULT 0 NOT NULL,
	note_private TEXT NULL,
	date_generation DATETIME NULL,
	date_printed DATETIME NULL,
	date_prepared DATETIME NULL,
	date_delivered DATETIME NULL,
	date_creation DATETIME NOT NULL,
	tms TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	fk_user_creat INTEGER NOT NULL,
	fk_user_modif INTEGER NULL,
	import_key VARCHAR(14) NULL
) ENGINE=innodb;
